[sdl]
output=dummy

[dosbox]
memsize=16

[render]
frameskip=0

[mixer]
nosound=true

[midi]
mididevice=none

[sblaster]
sbtype=none

[speaker]
pcspeaker=false

[joystick]
joysticktype=none

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[autoexec]
mount c /dosbox/c
c:
cd target_dir
target.com
exit
